theme: minima
title: Malasquez site
author: Eduardo A. Malasquez
email: e.malasquez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a personal site. Here you will find information about work projects and research.

# social links
twitter_username: Malasquez82
github_username:  Malasquez

show_excerpts: true # set to false to remove excerpts on the homepage
